platforms:
  - name: ubuntu-10.04
    driver_config:
      box: opscode-ubuntu-10.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-10.04.box
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
    run_list:
      - recipe[apt]
  - name: centos-6.3
    driver_config:
      box: opscode-centos-6.3
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
    run_list:
      - recipe[yum::epel]

suites:
  - name: system
    run_list:
      - recipe[ruby_build]
      - recipe[rbenv::system]
    json:
      rbenv:
        rubies:
          - 1.9.3-p327
        global: 1.9.3-p327
