backend_plugin: vagrant

platforms:
  - name: ubuntu-10.04
    vagrant_box: opscode-ubuntu-10.04
    vagrant_box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-10.04.box
    base_run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    vagrant_box: opscode-ubuntu-12.04
    vagrant_box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
    base_run_list:
      - recipe[apt]
  - name: centos-5.8
    vagrant_box: opscode-centos-5.8
    vagrant_box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-5.8.box
    base_run_list:
      - recipe[yum::epel]
  - name: centos-6.3
    vagrant_box: opscode-centos-6.3
    vagrant_box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
    base_run_list:
      - recipe[yum::epel]

suites:
  - name: stock_system_and_user
    run_list:
      - recipe[user::data_bag]
      - recipe[rvm::system]
      - recipe[rvm::user]
    json:
      users:
        - wigglebottom
      rvm:
        user_installs:
          - user: wigglebottom
            default_ruby: 1.8.7
