#!/bin/sh
# Strip charset from db dump, so it defaults to user's 
# Suggested by Ton Voon/Altinity

/usr/bin/perl -pi -e 's/DEFAULT CHARSET=ascii //' mysql.sql
/usr/bin/perl -pi -e 's/ DEFAULT CHARSET=ascii//' mysql.sql
